channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=23.1.2
- pip:
  - mlflow==2.5.0
  - cloudpickle==2.2.1
  - imbalanced-learn==0.11.0
  - numpy==1.24.0
  - pandas==2.0.3
  - psutil==5.9.5
  - scikit-learn==1.3.0
  - scipy==1.11.1
  - xgboost==1.7.6
name: mlflow-env
