name: Deploy API to Heroku

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Installation des dépendances
    - name: Install dependencies
      run: pip install -r api/requirements.txt

    # Vérifier si api.py a été modifié
    - name: Check if api.py was modified
      id: checkfile
      run: echo "::set-output name=api_modified::$(git diff --name-only HEAD~ HEAD | grep 'api/api.py')"

    # Exécution des tests sur api.py uniquement si api.py a été modifié
    - name: Run tests on api.py
      if: steps.checkfile.outputs.api_modified == 'api/api.py'
      run: pytest api/api.py

    # Connexion à Heroku et déploiement
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12 # This action deploys to Heroku
      with:
        heroku_api_key: ${{secrets.HEROKU_API_TOKEN}}
        heroku_app_name: "api2" #Must be unique in Heroku
        heroku_email: "xavier.parisot@gmail"
        usedocker: true # 
      
