name: Deploy API to Heroku

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install dependencies
    - name: Install dependencies
      run: pip install -r api/requirements.txt

    # Check if api2.py was modified
    - name: Check if api2.py was modified
      id: checkfile
      run: echo "::set-output name=api2_modified::$(git diff --name-only HEAD~ HEAD | grep 'api/api2.py')"

    # Run tests on api2.py only if api2.py was modified
    - name: Run tests on api2.py
      if: steps.checkfile.outputs.api2_modified == 'api/api2.py'
      run: pytest api/api2.py

    # Add Heroku remote
    - name: Add Heroku remote
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
      run: git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/api2.git

    # Deploy to Heroku
    - name: Push API folder to Heroku
      run: git subtree push --prefix api heroku main
